GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "route test 1",
    "source": {
        "lat": 0,
        "lng": 0
    },
    "destination": {
        "lat": 0,
        "lng": 0
    }
}